filebeat.prospectors:
- type: docker
  enabled: true
  containers:
    path: "/opt/containers"
    ids: 
      - 'fe185782efb4416ecebd322152aa04de9b68b097dd155adbeb6554ac5f5c8971'
output.logstash:
  hosts: ["logstash:5044"]
